theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
collections:
  menu:
    output: true
    permalink: /:name
  fragments:
    output: false